name: car-behavioral-cloning
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6.9
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - imageio
 pip:
    - moviepy
    - tensorflow-gpu